// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error)
	CreateCharacterAttribute(ctx context.Context, arg CreateCharacterAttributeParams) (CharacterAttribute, error)
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	CreateGameContext(ctx context.Context, arg CreateGameContextParams) (GameContext, error)
	CreateHistoryEntry(ctx context.Context, arg CreateHistoryEntryParams) (History, error)
	CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (InventoryItem, error)
	DeleteCharacter(ctx context.Context, id uuid.UUID) error
	DeleteCharacterAttribute(ctx context.Context, id uuid.UUID) error
	DeleteGame(ctx context.Context, id uuid.UUID) error
	DeleteGameContext(ctx context.Context, id uuid.UUID) error
	DeleteInventoryItem(ctx context.Context, id uuid.UUID) error
	EndGame(ctx context.Context, id uuid.UUID) (Game, error)
	GetCharacter(ctx context.Context, id uuid.UUID) (Character, error)
	GetCharacterAttribute(ctx context.Context, id uuid.UUID) (CharacterAttribute, error)
	GetGame(ctx context.Context, id uuid.UUID) (Game, error)
	GetGameContext(ctx context.Context, id uuid.UUID) (GameContext, error)
	GetHistoryEntry(ctx context.Context, id uuid.UUID) (History, error)
	GetInventoryItem(ctx context.Context, id uuid.UUID) (InventoryItem, error)
	LinkCharacterAttribute(ctx context.Context, arg LinkCharacterAttributeParams) error
	ListCharacterAttributesByType(ctx context.Context, arg ListCharacterAttributesByTypeParams) ([]CharacterAttribute, error)
	ListCharacters(ctx context.Context, gameID pgtype.UUID) ([]Character, error)
	ListGameContexts(ctx context.Context, gameID uuid.UUID) ([]GameContext, error)
	ListGameHistory(ctx context.Context, gameID uuid.UUID) ([]History, error)
	ListGameInventory(ctx context.Context, gameID uuid.UUID) ([]InventoryItem, error)
	ListGameTemplates(ctx context.Context) ([]Game, error)
	ListGames(ctx context.Context, arg ListGamesParams) ([]Game, error)
	SearchSimilarContexts(ctx context.Context, arg SearchSimilarContextsParams) ([]SearchSimilarContextsRow, error)
	SearchSimilarHistory(ctx context.Context, arg SearchSimilarHistoryParams) ([]SearchSimilarHistoryRow, error)
	StartGame(ctx context.Context, id uuid.UUID) (Game, error)
	UnlinkCharacterAttribute(ctx context.Context, arg UnlinkCharacterAttributeParams) error
	UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (Character, error)
	UpdateCharacterAttribute(ctx context.Context, arg UpdateCharacterAttributeParams) (CharacterAttribute, error)
	UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error)
	UpdateGameContextEmbedding(ctx context.Context, arg UpdateGameContextEmbeddingParams) error
	UpdateHistoryEmbedding(ctx context.Context, arg UpdateHistoryEmbeddingParams) error
	UpdateInventoryItem(ctx context.Context, arg UpdateInventoryItemParams) (InventoryItem, error)
}

var _ Querier = (*Queries)(nil)
